name: Windows (dotnet build and test)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  os-tests:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src/CSharp/EasyMicroservices.Database
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version:  |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
      - name: Restore dependencies
        run: dotnet restore ./EasyMicroservices.Database.sln
      - name: Build
        run: dotnet build ./EasyMicroservices.Database.sln --no-restore
      - name: Test
        run: dotnet test ./EasyMicroservices.Database.sln --no-build --verbosity normal