name: NuGet Push Public

on: [workflow_dispatch]

jobs:
  build-test-prep-push:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
        env:
          DOTNET_INSTALL_DIR: /usr/share/dotnet
      - name: Restore dependencies
        run: dotnet restore ./src/CSharp/EasyMicroservices.Database/EasyMicroservices.Database.sln
      - name: Build
        run: dotnet build ./src/CSharp/EasyMicroservices.Database/EasyMicroservices.Database.sln --no-restore
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
      - name: Test
        run: dotnet test ./src/CSharp/EasyMicroservices.Database/EasyMicroservices.Database.sln --no-build --verbosity normal
      - name: Create the package
        run: dotnet pack ./src/CSharp/EasyMicroservices.Database/EasyMicroservices.Database.sln --output nupkgs
      - name: Publish the package to NuGet.org
        run: dotnet nuget push nupkgs/*.nupkg -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
